In [67]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.svm import SVC
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [68]:
df = pd.read_csv("all_stocks_5yr.csv")
x = df.drop(['Name','volume','date'],axis='columns')
y = df['volume']
y = y/1000000
y = y.iloc[:6000]
x = x/10
x = x.iloc[:6000]
x.head(50)
# y.head()

     open   high    low  close
0   1.507  1.512  1.463  1.475
1   1.489  1.501  1.426  1.446
2   1.445  1.451  1.410  1.427
3   1.430  1.494  1.425  1.466
4   1.494  1.496  1.316  1.399
5   1.393  1.461  1.393  1.450
6   1.433  1.456  1.408  1.426
7   1.417  1.426  1.315  1.333
8   1.362  1.395  1.290  1.337
9   1.357  1.360  1.321  1.357
10  1.360  1.376  1.300  1.302
11  1.314  1.342  1.270  1.326
12  1.328  1.362  1.318  1.341
13  1.349  1.363  1.339  1.343
14  1.337  1.395  1.332  1.361
15  1.350  1.407  1.347  1.390
16  1.401  1.405  1.371  1.405
17  1.452  1.468  1.425  1.457
18  1.470  1.493  1.450  1.482
19  1.499  1.520  1.484  1.492
20  1.485  1.515  1.471  1.513
21  1.514  1.560  1.495  1.550
22  1.554  1.620  1.548  1.591
23  1.598  1.636  1.593  1.625
24  1.645  1.654  1.588  1.598
25  1.580  1.633  1.571  1.629
26  1.648  1.685  1.641  1.678
27  1.713  1.733  1.687  1.723
28  1.721  1.743  1.687  1.700
29  1.710  1.729  1.677  1.686
30  1.692  1.700  1.635  1.660
31  1.667  1.684  1.650  1.651
32  1.648  1.677  1.633  1.665
33  1.700  1.709  1.682  1.697
34  1.702  1.713  1.654  1.667
35  1.648  1.650  1.571  1.574
36  1.582  1.592  1.513  1.553
37  1.512  1.571  1.512  1.569
38  1.517  1.579  1.503  1.572
39  1.582  1.597  1.553  1.584
40  1.607  1.610  1.567  1.570
41  1.574  1.598  1.570  1.578
42  1.577  1.638  1.575  1.619
43  1.611  1.639  1.595  1.614
44  1.620  1.639  1.547  1.559
45  1.596  1.674  1.581  1.637
46  1.617  1.655  1.590  1.652
47  1.654  1.654  1.595  1.610
48  1.610  1.624  1.585  1.602
49  1.599  1.600  1.550  1.552

In [69]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
reg=linear_model.LinearRegression()
reg.fit(X_train, y_train)
X_train.shape

(4200, 4)

In [70]:
reg.coef_

array([  0.26246145,  24.62845852, -13.22564243, -11.78730836])

In [71]:
reg.intercept_

13.487379136972402

In [72]:
y_pred = reg.predict(X_test)
# y_test.shape

In [73]:
print('Mean squared error: %.2f'
      % mean_squared_error(y_test, y_pred))

Mean squared error: 626.78